### ISSUE TITLE
Installing this role inside the elao-symfony-standard

### ISSUE THREAD

**Issue by BenoitLeveque** [ElaoInfra/ansible-role-grafana#1]
Hi,

I'm trying to installs this role inside the elao/symfony-standard vagrant and i'm having some trouble to add the apt package for grafana.

i have update some files so far:

roles.yml : 

```
- src:     https://github.com/ElaoInfra/ansible-role-grafana
  name:    elao.grafana
  version: origin/1.0
```

playbook.yml

```

---
- hosts: all
  roles:
    - { role: elao.grafana }
```

all.yml

```
elao_apt_repositories:
  - source: deb https://packagecloud.io/grafana/stable/debian/ wheezy main
    key:
      url: https://packagecloud.io/gpg.key
      id: ???
```

Where can i find the id for the grafana package ?
